### ISSUE TITLE
Grammatical problem

### ISSUE THREAD

**Issue by Ignatus** [johnschult/jquery.countdown360#2]
When countdown is 2,3,4,5.... "second" have a "s" : "seconds".
When countdown is 1 "second" don't have a "s" : "second".

When countdown is 0, "second" have a "s" : "seconds

Problem is here :  label = secondsLeft === 1 ? this.settings.label[0] : this.settings.label[1],

Resolved by : label = secondsLeft <= 1 ? this.settings.label[0] : this.settings.label[1],

**Comment by johnschult** [comment]
In English, zero (0) quantity uses the plural form of a word. The plugin has only been written in English, however I am certainly open to localization if anyone wants to do the work and submit a Pull Request :smile:
