### ISSUE TITLE
Can I remove the number inside circle?

### ISSUE THREAD

**Issue by davidwillianx** [johnschult/jquery.countdown360#9]
I would like to show one countdown without this number, is it possible?

**Comment by johnschult** [comment]
The easiest way to do this without adding some sort of boolean flag (which I would prefer :smile:) would be to set `fontColor` to be the same value as `fillColor` in the plugin configuration.

In [this fiddle](http://jsfiddle.net/651zL9v0/) I set `fontColor` to be the same as the default `fillColor` value of `#8ac575`.
